use std::{cell::RefCell, collections::VecDeque, ffi::OsStr, io::Cursor, path::Path};

use anyhow::{Context, Result, anyhow, bail};
use bytes::Bytes;
use chrono::{DateTime, NaiveDate, Utc};
use percent_encoding::percent_decode_str;

use crate::{
    api_client::{ApiClient, LoginError, PhotoNotFound, SortBy},
    cli::SourceSize,
    ftp::{
        ConnectionLost, Credentials, EntryKind, FtpAddress, FtpTransport, InvalidFtpResponse,
        validate_path,
    },
    http::Url,
    metadata::{Location, Metadata},
};

/// File name extensions of the formats the `image` dependency is built with
const PHOTO_EXTENSIONS: [&str; 3] = ["jpg", "jpeg", "png"];

/// Directories holding files generated by the server rather than photos of the user. Synology
/// Photos keeps its thumbnails in `@eaDir`, and those are real JPEG files.
const EXCLUDED_DIRECTORIES: [&str; 1] = ["@eaDir"];

/// Bounds how deep the traversal descends, in case of a deeply nested or unexpectedly large tree
const MAX_DEPTH: usize = 16;

/// One reconnect is enough to recover from the far most common failure: the server dropping an idle
/// session between two photos
const MAX_ATTEMPTS: usize = 2;

const ANONYMOUS_USER: &str = "anonymous";

/// Reads photos from a directory on an FTP server
pub struct FtpApiClient<T> {
    address: FtpAddress,
    credentials: Credentials,
    /// Absolute path of the directory the share link points at, and the root of the traversal
    root: String,
    /// [ApiClient] takes `&self` throughout, while an FTP session is inherently stateful. A
    /// [RefCell] rather than a [std::sync::Mutex] because the client is moved into the photo
    /// fetching thread instead of being shared, and because a poisoned mutex would turn every
    /// remaining photo of the session into an error screen.
    ///
    /// Overlapping borrows would panic, which is prevented by borrowing it in exactly one place:
    /// [FtpApiClient::with_reconnect].
    transport: RefCell<T>,

    /// Path and bytes of the most recently downloaded photo, read by [ApiClient::get_exif]
    last_photo: RefCell<Option<(String, Bytes)>>,
}

impl<T: FtpTransport> FtpApiClient<T> {
    pub fn build(transport: T, share_link: &Url) -> Result<Self> {
        let (address, credentials, root) = parse_share_link(share_link)?;
        Ok(Self {
            address,
            credentials,
            root,
            transport: RefCell::new(transport),
            last_photo: RefCell::new(None),
        })
    }

    pub fn with_password(mut self, password: &Option<String>) -> Self {
        if let Some(password) = password {
            self.credentials.password = password.clone();
        }
        self
    }

    /// Lists every photo below [FtpApiClient::root], breadth first
    fn walk(&self) -> Result<Vec<FtpPhoto>> {
        let mut photos = vec![];
        /* Directories left to visit, as paths relative to the root, with their depth */
        let mut pending = VecDeque::from([(String::new(), 0)]);

        while let Some((directory, depth)) = pending.pop_front() {
            let path = self.absolute(&directory);
            let entries = match self.with_reconnect(|transport| transport.list_dir(&path)) {
                Ok(entries) => entries,
                Err(error) if directory.is_empty() => {
                    /* Not being able to list the directory the share link points at is fatal,
                     * while a directory deeper down may legitimately have been removed or be
                     * inaccessible. */
                    return Err(error.context(format!("Cannot list {path}")));
                }
                Err(error) => {
                    log::warn!("Skipping directory {path}: {error}");
                    continue;
                }
            };

            for entry in entries {
                if entry.name.starts_with('.')
                    || EXCLUDED_DIRECTORIES.contains(&entry.name.as_str())
                {
                    /* Hidden entries, the "." and ".." entries of the listed directory, and
                     * directories of server-generated files */
                    continue;
                }
                let relative = join(&directory, &entry.name);
                match entry.kind {
                    EntryKind::Directory if depth < MAX_DEPTH => {
                        pending.push_back((relative, depth + 1));
                    }
                    EntryKind::Directory => log::warn!(
                        "Not descending into {relative}: maximum depth of {MAX_DEPTH} reached"
                    ),
                    /* Symlinks are never followed, which rules out traversal loops */
                    EntryKind::Symlink => log::debug!("Skipping symbolic link {relative}"),
                    EntryKind::File if is_photo(&entry.name) => photos.push(FtpPhoto {
                        path: relative,
                        modified: entry.modified,
                    }),
                    EntryKind::File => (),
                }
            }
        }

        Ok(photos)
    }

    /// Runs an operation, reconnecting and retrying it once if the connection turned out to be dead
    fn with_reconnect<R>(&self, mut operation: impl FnMut(&mut T) -> Result<R>) -> Result<R> {
        let mut last_error = None;
        for attempt in 1..=MAX_ATTEMPTS {
            let mut transport = self.transport.borrow_mut();
            if !transport.is_connected()
                && let Err(error) = transport.connect(&self.address, &self.credentials)
            {
                log::warn!("Cannot connect to the FTP server (attempt {attempt}): {error}");
                transport.disconnect();
                last_error = Some(error);
                continue;
            }
            match operation(&mut transport) {
                Ok(value) => return Ok(value),
                Err(error) if error.is::<ConnectionLost>() => {
                    log::warn!("FTP connection lost (attempt {attempt}): {error}");
                    transport.disconnect();
                    last_error = Some(error);
                }
                /* Anything else is a decision of the server, which retrying would not change */
                Err(error) => return Err(error),
            }
        }
        Err(last_error.expect("at least one attempt must have failed"))
    }

    /// [ApiClient::get_exif] does not receive the photo's bytes, and [crate::slideshow::Slideshow]
    /// calls it right after [ApiClient::get_photo_bytes], so the bytes of the photo being displayed
    /// are taken from here rather than downloaded a second time. [Bytes] is reference counted, so
    /// this keeps one photo's buffer alive and copies nothing.
    fn cached_photo_bytes(&self, path: &str) -> Option<Bytes> {
        match self.last_photo.borrow().as_ref() {
            Some((cached_path, bytes)) if cached_path == path => Some(bytes.clone()),
            _ => {
                log::debug!(
                    "Bytes of {path} are not available, falling back to its modification time"
                );
                None
            }
        }
    }

    /// Turns a path relative to [FtpApiClient::root] into an absolute one
    fn absolute(&self, relative: &str) -> String {
        if relative.is_empty() {
            self.root.clone()
        } else if self.root.ends_with('/') {
            format!("{}{relative}", self.root)
        } else {
            format!("{}/{relative}", self.root)
        }
    }
}

impl<T: FtpTransport> ApiClient for FtpApiClient<T> {
    type Photo = FtpPhoto;

    fn is_logged_in(&self) -> bool {
        self.transport
            .try_borrow()
            .is_ok_and(|transport| transport.is_connected())
    }

    fn login(&self) -> Result<(), LoginError> {
        /* Every failure to establish the session terminates the application, matching the other
         * backends: a wrong address, user or password is not worth retrying. Failures occurring
         * later, while the slideshow runs, are recoverable and must not be reported as a
         * LoginError. */
        self.transport
            .borrow_mut()
            .connect(&self.address, &self.credentials)
            .map_err(LoginError)
    }

    fn get_photo_metadata(&self, sort_by: SortBy) -> Result<Vec<Self::Photo>> {
        let mut photos = self.walk()?;
        log::info!("Found {} photos in {}", photos.len(), self.root);
        sort_photos(&mut photos, sort_by);
        Ok(photos)
    }

    /// The time a photo was taken is only known from its own EXIF metadata; an FTP server has
    /// nothing else to offer. Photos without it, such as scans or downloads, fall back to the
    /// modification time reported by the server.
    fn get_exif(&self, photo: &Self::Photo) -> Result<impl Metadata> {
        let date = self
            .cached_photo_bytes(&photo.path)
            .as_deref()
            .and_then(exif_date)
            .or(photo.modified);
        let Some(date) = date else {
            bail!(
                "Neither EXIF metadata nor a modification time is available for {}",
                photo.path
            )
        };
        Ok(FtpMetadata { date })
    }

    /// [SourceSize] does not apply, as an FTP server offers no scaled down versions of a file
    fn get_photo_bytes(&self, photo: &Self::Photo, _: SourceSize) -> Result<Bytes> {
        let path = self.absolute(&photo.path);
        let bytes = self
            .with_reconnect(|transport| transport.retrieve(&path))
            .map_err(map_photo_not_found)?;
        self.last_photo
            .replace(Some((photo.path.clone(), bytes.clone())));
        Ok(bytes)
    }
}

/// A photo found below the directory the share link points at
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FtpPhoto {
    /// Path relative to the traversal root, for example `2025/summer/IMG_1234.jpg`. Doubles as the
    /// [SortBy::FileName] key, which keeps photos of one directory together.
    pub path: String,

    /// Modification time reported by the server. Serves as the [SortBy::TakenTime] key, and is
    /// [None] when the server reported none.
    pub modified: Option<DateTime<Utc>>,
}

/// An FTP server exposes no geotagging, so [Metadata::location] is always empty
struct FtpMetadata {
    date: DateTime<Utc>,
}

impl Metadata for FtpMetadata {
    fn date(&self) -> DateTime<Utc> {
        self.date
    }

    fn location(&self) -> Location {
        Location::default()
    }
}

/// Reads the time a photo was taken from its EXIF metadata, if it has any
fn exif_date(bytes: &[u8]) -> Option<DateTime<Utc>> {
    let exif = exif::Reader::new()
        .read_from_container(&mut Cursor::new(bytes))
        .inspect_err(|error| log::debug!("No EXIF metadata: {error}"))
        .ok()?;
    let field = exif.get_field(exif::Tag::DateTimeOriginal, exif::In::PRIMARY)?;
    let exif::Value::Ascii(values) = &field.value else {
        return None;
    };
    let date_time = exif::DateTime::from_ascii(values.first()?)
        .inspect_err(|error| log::debug!("Unusable EXIF DateTimeOriginal: {error}"))
        .ok()?;
    /* DateTimeOriginal is the local time where the photo was taken and carries no time zone. It is
     * displayed as it is rather than shifted by a guessed offset, which is also what the Immich
     * backend does with its localDateTime. */
    NaiveDate::from_ymd_opt(
        date_time.year.into(),
        date_time.month.into(),
        date_time.day.into(),
    )?
    .and_hms_opt(
        date_time.hour.into(),
        date_time.minute.into(),
        date_time.second.into(),
    )
    .map(|naive| naive.and_utc())
}

/// Sorts photos in ascending order, which is what [crate::slideshow::Slideshow] expects. Photos
/// whose modification time is unknown come first, and the file name breaks ties to keep the order
/// deterministic.
fn sort_photos(photos: &mut [FtpPhoto], sort_by: SortBy) {
    photos.sort_by(|a, b| match sort_by {
        SortBy::TakenTime => a
            .modified
            .cmp(&b.modified)
            .then_with(|| a.path.cmp(&b.path)),
        SortBy::FileName => a.path.cmp(&b.path),
    });
}

/// A file that is gone is reported as 550, and by some servers as 450 or 451
fn map_photo_not_found(error: anyhow::Error) -> anyhow::Error {
    use suppaftp::Status::{ActionAborted, FileUnavailable, RequestFileActionIgnored};
    match error.downcast_ref::<InvalidFtpResponse>() {
        Some(InvalidFtpResponse {
            status: FileUnavailable | RequestFileActionIgnored | ActionAborted,
            ..
        }) => anyhow!(PhotoNotFound(error)),
        _ => error,
    }
}

fn is_photo(name: &str) -> bool {
    Path::new(name)
        .extension()
        .and_then(OsStr::to_str)
        .is_some_and(|extension| {
            PHOTO_EXTENSIONS
                .iter()
                .any(|photo| extension.eq_ignore_ascii_case(photo))
        })
}

fn join(directory: &str, name: &str) -> String {
    if directory.is_empty() {
        name.to_string()
    } else {
        format!("{directory}/{name}")
    }
}

/// Extracts the server address, the credentials and the root directory from an `ftp://` link
fn parse_share_link(share_link: &Url) -> Result<(FtpAddress, Credentials, String)> {
    /* The link is never quoted in an error message, since it may contain a password */
    if share_link.scheme() != "ftp" {
        bail!("Invalid FTP share link: expected an ftp:// URL");
    }
    let host = share_link
        .host_str()
        .context("Invalid FTP share link: no host name")?
        .to_string();
    /* "ftp" is a special scheme in the URL standard, so its default port is known */
    let port = share_link
        .port_or_known_default()
        .context("Invalid FTP share link: no port")?;

    let user = decode(share_link.username())?;
    let user = if user.is_empty() {
        ANONYMOUS_USER.to_string()
    } else {
        user
    };
    let password = match share_link.password() {
        Some(password) => {
            log::warn!(
                "Providing the password in the share link exposes it to other users of this \
                 machine; consider using the --password option instead"
            );
            decode(password)?
        }
        /* Convention for anonymous logins, which many servers require to look like an address */
        None if user == ANONYMOUS_USER => format!("{ANONYMOUS_USER}@"),
        None => String::new(),
    };

    let root = normalize_root(&decode(share_link.path())?);
    validate_path(&root)?;

    Ok((
        FtpAddress { host, port },
        Credentials { user, password },
        root,
    ))
}

/// A [Url] keeps its components percent-encoded, while FTP commands take the literal name
fn decode(value: &str) -> Result<String> {
    Ok(percent_decode_str(value).decode_utf8()?.to_string())
}

fn normalize_root(path: &str) -> String {
    let trimmed = path.trim_end_matches('/');
    if trimmed.is_empty() {
        "/".to_string()
    } else {
        trimmed.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use chrono::TimeZone;
    use mockall::{Sequence, predicate::eq};
    use suppaftp::Status;

    use crate::ftp::{DirEntry, MockFtpTransport};

    const SHARE_LINK: &str = "ftp://joe@fake.nas/Photos";

    #[test]
    fn parse_share_link_extracts_address_user_and_root() {
        fn test_case(share_link: &str, expected: (&str, u16, &str, &str)) {
            let (expected_host, expected_port, expected_user, expected_root) = expected;

            let (address, credentials, root) =
                parse_share_link(&Url::parse(share_link).unwrap()).unwrap();

            assert_eq!(address.host, expected_host, "link was {share_link}");
            assert_eq!(address.port, expected_port, "link was {share_link}");
            assert_eq!(credentials.user, expected_user, "link was {share_link}");
            assert_eq!(root, expected_root, "link was {share_link}");
        }

        test_case(
            "ftp://fake.nas/Photos",
            ("fake.nas", 21, "anonymous", "/Photos"),
        );
        test_case(
            "ftp://joe@fake.nas:2121/a/b",
            ("fake.nas", 2121, "joe", "/a/b"),
        );
        /* A trailing slash is not part of the directory name */
        test_case(
            "ftp://fake.nas/Photos/",
            ("fake.nas", 21, "anonymous", "/Photos"),
        );
        /* The whole server, when no directory is given */
        test_case("ftp://fake.nas", ("fake.nas", 21, "anonymous", "/"));
    }

    #[test]
    fn parse_share_link_percent_decodes_user_and_root() {
        let share_link = Url::parse("ftp://joe%40corp@fake.nas/My%20Photos").unwrap();

        let (_, credentials, root) = parse_share_link(&share_link).unwrap();

        assert_eq!(credentials.user, "joe@corp");
        assert_eq!(root, "/My Photos");
    }

    #[test]
    fn parse_share_link_takes_the_password_from_the_link() {
        let share_link = Url::parse("ftp://joe:secret@fake.nas/Photos").unwrap();

        let (_, credentials, _) = parse_share_link(&share_link).unwrap();

        assert_eq!(credentials.password, "secret");
    }

    #[test]
    fn parse_share_link_defaults_to_an_anonymous_login() {
        let share_link = Url::parse("ftp://fake.nas/Photos").unwrap();

        let (_, credentials, _) = parse_share_link(&share_link).unwrap();

        assert_eq!(credentials.user, "anonymous");
        assert_eq!(credentials.password, "anonymous@");
    }

    #[test]
    fn parse_share_link_rejects_a_non_ftp_link() {
        for share_link in [
            "https://fake.nas/Photos",
            "ftps://fake.nas/Photos",
            "file:///Photos",
        ] {
            let result = parse_share_link(&Url::parse(share_link).unwrap());

            assert!(result.is_err(), "link was {share_link}");
        }
    }

    #[test]
    fn parse_share_link_error_does_not_reveal_the_password() {
        let share_link = Url::parse("https://joe:secret@fake.nas/Photos").unwrap();

        let error = parse_share_link(&share_link).unwrap_err();

        let message = format!("{error:#}");
        assert!(!message.contains("secret"), "was {message}");
    }

    #[test]
    fn with_password_overrides_the_password_from_the_link() {
        let client = new_client(
            MockFtpTransport::new(),
            "ftp://joe:from_link@fake.nas/Photos",
        )
        .with_password(&Some("from_option".to_string()));

        assert_eq!(client.credentials.password, "from_option");
    }

    #[test]
    fn with_password_keeps_the_link_password_when_no_option_is_given() {
        let client = new_client(
            MockFtpTransport::new(),
            "ftp://joe:from_link@fake.nas/Photos",
        )
        .with_password(&None);

        assert_eq!(client.credentials.password, "from_link");
    }

    #[test]
    fn get_photo_metadata_lists_photos_recursively() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_list_dir()
            .with(eq("/Photos"))
            .return_once(|_| {
                Ok(vec![
                    new_file("a.jpg", None),
                    new_directory("summer"),
                    new_file("notes.txt", None),
                ])
            });
        transport
            .expect_list_dir()
            .with(eq("/Photos/summer"))
            .return_once(|_| Ok(vec![new_file("b.jpeg", None), new_directory("beach")]));
        transport
            .expect_list_dir()
            .with(eq("/Photos/summer/beach"))
            .return_once(|_| Ok(vec![new_file("c.png", None)]));
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert_eq!(
            paths(&photos),
            vec!["a.jpg", "summer/b.jpeg", "summer/beach/c.png"]
        );
    }

    #[test]
    fn get_photo_metadata_only_returns_supported_image_files() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport.expect_list_dir().return_once(|_| {
            Ok(vec![
                new_file("notes.txt", None),
                new_file("movie.MP4", None),
                /* A regression guard: matching the extension anywhere in the name would let this
                 * one through */
                new_file("photo.jpg.txt", None),
                new_file("raw.heic", None),
                new_file("IMG.JPG", None),
                new_file("scan.jpeg", None),
                new_file("shot.PnG", None),
                /* No extension at all */
                new_file("jpg", None),
            ])
        });
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert_eq!(paths(&photos), vec!["IMG.JPG", "scan.jpeg", "shot.PnG"]);
    }

    #[test]
    fn get_photo_metadata_skips_hidden_and_generated_directories() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_list_dir()
            /* Descending into any of these would be a failure */
            .with(eq("/Photos"))
            .times(1)
            .return_once(|_| {
                Ok(vec![
                    new_directory("@eaDir"),
                    new_directory(".cache"),
                    /* MLSD reports these for the listed directory itself */
                    new_directory("."),
                    new_directory(".."),
                    new_file(".hidden.jpg", None),
                    new_file("visible.jpg", None),
                ])
            });
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert_eq!(paths(&photos), vec!["visible.jpg"]);
    }

    #[test]
    fn get_photo_metadata_does_not_follow_symlinks() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_list_dir()
            .with(eq("/Photos"))
            .times(1)
            .return_once(|_| {
                Ok(vec![
                    DirEntry {
                        name: "loop".to_string(),
                        kind: EntryKind::Symlink,
                        modified: None,
                    },
                    new_file("a.jpg", None),
                ])
            });
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert_eq!(paths(&photos), vec!["a.jpg"]);
    }

    #[test]
    fn get_photo_metadata_stops_descending_at_the_maximum_depth() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        /* Every directory contains one photo and one more directory, so without a limit the
         * traversal would not terminate */
        transport.expect_list_dir().returning(|path| {
            Ok(vec![
                new_file("a.jpg", None),
                new_directory(&format!("d{}", path.len())),
            ])
        });
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert_eq!(
            photos.len(),
            MAX_DEPTH + 1,
            "expected the root and {MAX_DEPTH} levels below it"
        );
    }

    #[test]
    fn get_photo_metadata_skips_a_directory_that_cannot_be_listed() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_list_dir()
            .with(eq("/Photos"))
            .return_once(|_| Ok(vec![new_directory("gone"), new_file("a.jpg", None)]));
        transport
            .expect_list_dir()
            .with(eq("/Photos/gone"))
            .return_once(|_| Err(invalid_response(Status::FileUnavailable)));
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert_eq!(paths(&photos), vec!["a.jpg"]);
    }

    #[test]
    fn get_photo_metadata_fails_when_the_root_directory_cannot_be_listed() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_list_dir()
            .returning(|_| Err(invalid_response(Status::FileUnavailable)));
        let client = new_client(transport, SHARE_LINK);

        let result = client.get_photo_metadata(SortBy::FileName);

        assert!(result.is_err());
    }

    #[test]
    fn get_photo_metadata_returns_no_photos_when_nothing_matches() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_list_dir()
            .return_once(|_| Ok(vec![new_file("notes.txt", None)]));
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert!(photos.is_empty());
    }

    #[test]
    fn get_photo_metadata_sorts_by_modification_time_ascending() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport.expect_list_dir().return_once(|_| {
            Ok(vec![
                new_file("newest.jpg", Some(3)),
                new_file("oldest.jpg", Some(1)),
                new_file("unknown.jpg", None),
                new_file("middle.jpg", Some(2)),
            ])
        });
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::TakenTime).unwrap();

        assert_eq!(
            paths(&photos),
            /* Photos of an unknown date come first */
            vec!["unknown.jpg", "oldest.jpg", "middle.jpg", "newest.jpg"]
        );
    }

    #[test]
    fn get_photo_metadata_sorts_by_path_ascending() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_list_dir()
            .with(eq("/Photos"))
            .return_once(|_| Ok(vec![new_file("b.jpg", Some(1)), new_directory("a")]));
        transport
            .expect_list_dir()
            .with(eq("/Photos/a"))
            .return_once(|_| Ok(vec![new_file("c.jpg", Some(2))]));
        let client = new_client(transport, SHARE_LINK);

        let photos = client.get_photo_metadata(SortBy::FileName).unwrap();

        assert_eq!(paths(&photos), vec!["a/c.jpg", "b.jpg"]);
    }

    #[test]
    fn get_photo_bytes_retrieves_an_absolute_path() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_retrieve()
            .with(eq("/Photos/summer/b.jpeg"))
            .return_once(|_| Ok(Bytes::from_static(&[42, 1, 255, 50])));
        let client = new_client(transport, SHARE_LINK);

        let bytes = client
            .get_photo_bytes(&new_photo("summer/b.jpeg", None), SourceSize::L)
            .unwrap();

        assert_eq!(bytes, Bytes::from_static(&[42, 1, 255, 50]));
    }

    #[test]
    fn when_the_connection_is_lost_then_get_photo_bytes_reconnects_and_retries() {
        let mut sequence = Sequence::new();
        let mut transport = MockFtpTransport::new();
        transport
            .expect_is_connected()
            .times(1)
            .in_sequence(&mut sequence)
            .return_const(true);
        transport
            .expect_retrieve()
            .times(1)
            .in_sequence(&mut sequence)
            .returning(|_| Err(anyhow!(ConnectionLost(anyhow!("connection reset")))));
        transport
            .expect_disconnect()
            .times(1)
            .in_sequence(&mut sequence)
            .return_const(());
        transport
            .expect_is_connected()
            .times(1)
            .in_sequence(&mut sequence)
            .return_const(false);
        transport
            .expect_connect()
            .times(1)
            .in_sequence(&mut sequence)
            .returning(|_, _| Ok(()));
        transport
            .expect_retrieve()
            .times(1)
            .in_sequence(&mut sequence)
            .return_once(|_| Ok(Bytes::from_static(&[42])));
        let client = new_client(transport, SHARE_LINK);

        let bytes = client
            .get_photo_bytes(&new_photo("a.jpg", None), SourceSize::L)
            .unwrap();

        assert_eq!(bytes, Bytes::from_static(&[42]));
    }

    #[test]
    fn when_reconnecting_keeps_failing_then_the_error_is_not_a_login_error() {
        let mut transport = MockFtpTransport::new();
        transport.expect_is_connected().return_const(false);
        transport
            .expect_connect()
            .times(MAX_ATTEMPTS)
            .returning(|_, _| Err(anyhow!("no route to host")));
        transport.expect_disconnect().return_const(());
        let client = new_client(transport, SHARE_LINK);

        let error = client
            .get_photo_bytes(&new_photo("a.jpg", None), SourceSize::L)
            .unwrap_err();

        assert!(
            !error.is::<LoginError>(),
            "a failure while the slideshow runs must not terminate the application"
        );
    }

    #[test]
    fn when_a_photo_is_gone_then_it_is_reported_as_not_found_without_reconnecting() {
        let mut transport = MockFtpTransport::new();
        transport.expect_is_connected().return_const(true);
        /* Reconnecting would not bring the file back */
        transport.expect_connect().never();
        transport
            .expect_retrieve()
            .times(1)
            .return_once(|_| Err(invalid_response(Status::FileUnavailable)));
        let client = new_client(transport, SHARE_LINK);

        let error = client
            .get_photo_bytes(&new_photo("a.jpg", None), SourceSize::L)
            .unwrap_err();

        assert!(
            error.is::<PhotoNotFound>(),
            "the slideshow must skip the photo instead of showing the error screen"
        );
    }

    #[test]
    fn login_failure_is_reported_as_a_login_error() {
        let mut transport = MockFtpTransport::new();
        transport
            .expect_connect()
            .times(1)
            .returning(|_, _| Err(anyhow!("530 Login incorrect")));
        let client = new_client(transport, SHARE_LINK);

        let result = client.login();

        assert!(result.is_err());
    }

    #[test]
    fn login_passes_the_address_and_credentials_to_the_transport() {
        let mut transport = MockFtpTransport::new();
        transport
            .expect_connect()
            .withf(|address, credentials| {
                address
                    == &(FtpAddress {
                        host: "fake.nas".to_string(),
                        port: 2121,
                    })
                    && credentials.user == "joe"
                    && credentials.password == "secret"
            })
            .times(1)
            .returning(|_, _| Ok(()));
        let client = new_client(transport, "ftp://joe:secret@fake.nas:2121/Photos");

        assert!(client.login().is_ok());
    }

    #[test]
    fn is_logged_in_reflects_the_transport_state() {
        let mut transport = MockFtpTransport::new();
        transport.expect_is_connected().return_const(true);
        assert!(new_client(transport, SHARE_LINK).is_logged_in());

        let mut transport = MockFtpTransport::new();
        transport.expect_is_connected().return_const(false);
        assert!(!new_client(transport, SHARE_LINK).is_logged_in());
    }

    #[test]
    fn get_exif_returns_the_modification_time_without_a_location() {
        let client = new_client(MockFtpTransport::new(), SHARE_LINK);
        let photo = new_photo("a.jpg", Some(1));

        let metadata = client.get_exif(&photo).unwrap();

        assert_eq!(metadata.date(), timestamp(1));
        let location = metadata.location();
        assert_eq!((location.area, location.country), (None, None));
    }

    #[test]
    fn get_exif_fails_when_no_modification_time_is_known() {
        let client = new_client(MockFtpTransport::new(), SHARE_LINK);
        let photo = new_photo("a.jpg", None);

        let result = client.get_exif(&photo);

        assert!(result.is_err());
    }

    #[test]
    fn get_exif_prefers_the_date_the_photo_was_taken() {
        let mut transport = MockFtpTransport::new();
        expect_connected(&mut transport);
        transport
            .expect_retrieve()
            .return_once(|_| Ok(jpeg_with_exif_date("2019:07:14 09:12:45")));
        let client = new_client(transport, SHARE_LINK);
        let photo = new_photo("a.jpg", Some(1));

        client.get_photo_bytes(&photo, SourceSize::L).unwrap();
        let metadata = client.get_exif(&photo).unwrap();

        assert_eq!(
            metadata.date(),
            Utc.with_ymd_and_hms(2019, 7, 14, 9, 12, 45).unwrap(),
            "the EXIF date must win over the modification time"
        );
    }

    #[test]
    fn get_exif_falls_back_to_the_modification_time_without_usable_exif_metadata() {
        for bytes in [
            /* An empty JPEG carries no EXIF metadata at all */
            Bytes::from_static(&[0xFF, 0xD8, 0xFF, 0xD9]),
            /* Nor does something that is not an image */
            Bytes::from_static(b"not an image"),
            jpeg_with_exif_date("    :  :     :  :  "),
        ] {
            let mut transport = MockFtpTransport::new();
            expect_connected(&mut transport);
            transport.expect_retrieve().return_once(|_| Ok(bytes));
            let client = new_client(transport, SHARE_LINK);
            let photo = new_photo("a.jpg", Some(1));

            client.get_photo_bytes(&photo, SourceSize::L).unwrap();
            let metadata = client.get_exif(&photo).unwrap();

            assert_eq!(metadata.date(), timestamp(1));
        }
    }

    #[test]
    fn get_exif_falls_back_to_the_modification_time_without_downloading_the_photo_again() {
        let mut transport = MockFtpTransport::new();
        /* Downloading a photo just to read its date would double the transferred data */
        transport.expect_retrieve().never();
        let client = new_client(transport, SHARE_LINK);
        let photo = new_photo("never_downloaded.jpg", Some(1));

        let metadata = client.get_exif(&photo).unwrap();

        assert_eq!(metadata.date(), timestamp(1));
    }

    /// Builds the smallest JPEG a DateTimeOriginal can be read from: an APP1 segment holding a TIFF
    /// structure whose IFD0 points at an Exif IFD with a single entry. No pixel data is needed, as
    /// EXIF metadata lives in the marker segments.
    fn jpeg_with_exif_date(date_time_original: &str) -> Bytes {
        const TIFF_HEADER_SIZE: u32 = 8;
        /* Entry count, one 12 byte entry, and the offset of the next directory */
        const IFD_SIZE: u32 = 2 + 12 + 4;
        const EXIF_IFD_OFFSET: u32 = TIFF_HEADER_SIZE + IFD_SIZE;
        const VALUE_OFFSET: u32 = EXIF_IFD_OFFSET + IFD_SIZE;
        const TAG_EXIF_IFD_POINTER: u16 = 0x8769;
        const TAG_DATE_TIME_ORIGINAL: u16 = 0x9003;
        const TYPE_ASCII: u16 = 2;
        const TYPE_LONG: u16 = 4;

        let mut value = date_time_original.as_bytes().to_vec();
        value.push(0);
        assert_eq!(value.len(), 20, "an EXIF date is 19 characters and a NUL");

        let mut tiff = vec![];
        /* Little-endian TIFF header */
        tiff.extend(b"II");
        tiff.extend(42u16.to_le_bytes());
        tiff.extend(TIFF_HEADER_SIZE.to_le_bytes());
        /* IFD0, holding only a pointer to the Exif IFD */
        tiff.extend(1u16.to_le_bytes());
        tiff.extend(TAG_EXIF_IFD_POINTER.to_le_bytes());
        tiff.extend(TYPE_LONG.to_le_bytes());
        tiff.extend(1u32.to_le_bytes());
        tiff.extend(EXIF_IFD_OFFSET.to_le_bytes());
        tiff.extend(0u32.to_le_bytes());
        /* Exif IFD, holding only the date */
        tiff.extend(1u16.to_le_bytes());
        tiff.extend(TAG_DATE_TIME_ORIGINAL.to_le_bytes());
        tiff.extend(TYPE_ASCII.to_le_bytes());
        tiff.extend(u32::try_from(value.len()).unwrap().to_le_bytes());
        tiff.extend(VALUE_OFFSET.to_le_bytes());
        tiff.extend(0u32.to_le_bytes());
        assert_eq!(u32::try_from(tiff.len()).unwrap(), VALUE_OFFSET);
        tiff.extend(value);

        let mut jpeg = vec![0xFF, 0xD8, 0xFF, 0xE1];
        /* The segment length covers itself, the identifier and the TIFF structure */
        jpeg.extend(u16::try_from(2 + 6 + tiff.len()).unwrap().to_be_bytes());
        jpeg.extend(b"Exif\0\0");
        jpeg.extend(tiff);
        jpeg.extend([0xFF, 0xD9]);
        Bytes::from(jpeg)
    }

    #[test]
    fn the_exif_test_fixture_is_readable() {
        /* Without this, a broken fixture would silently exercise only the fallback path above */
        let date = exif_date(&jpeg_with_exif_date("2019:07:14 09:12:45"));

        assert_eq!(
            date,
            Some(Utc.with_ymd_and_hms(2019, 7, 14, 9, 12, 45).unwrap())
        );
    }

    fn new_client<T: FtpTransport>(transport: T, share_link: &str) -> FtpApiClient<T> {
        FtpApiClient::build(transport, &Url::parse(share_link).unwrap()).unwrap()
    }

    /// Most tests are not about connection handling, so the session is simply always up
    fn expect_connected(transport: &mut MockFtpTransport) {
        transport.expect_is_connected().return_const(true);
    }

    fn new_file(name: &str, modified: Option<u32>) -> DirEntry {
        DirEntry {
            name: name.to_string(),
            kind: EntryKind::File,
            modified: modified.map(timestamp),
        }
    }

    fn new_directory(name: &str) -> DirEntry {
        DirEntry {
            name: name.to_string(),
            kind: EntryKind::Directory,
            modified: None,
        }
    }

    fn new_photo(path: &str, modified: Option<u32>) -> FtpPhoto {
        FtpPhoto {
            path: path.to_string(),
            modified: modified.map(timestamp),
        }
    }

    fn timestamp(day: u32) -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2025, 10, day, 14, 33, 7).unwrap()
    }

    fn invalid_response(status: Status) -> anyhow::Error {
        anyhow!(InvalidFtpResponse {
            status,
            message: "test".to_string(),
        })
    }

    fn paths(photos: &[FtpPhoto]) -> Vec<&str> {
        photos.iter().map(|photo| photo.path.as_str()).collect()
    }
}
